### ISSUE TITLE
Problem with .pem key

### ISSUE THREAD

**Issue by ghost** [ongoworks/meteor-google-spreadsheets#14]
Since last week I am getting some errors:

```
Error: SignFinal error
W20160427-12:42:39.368(3)? (STDERR) 139835110377344:error:0906D06C:PEM routines:PEM_read_bio:no start line:../deps/openssl/openssl/crypto/pem/pem_lib.c:696:Expecting: ANY PRIVATE KEY
```

I think something went wrong mby with some last updates or etc, coz earlier everything was good.
And my code looks like this:

```
 serverRoot = fs.realpathSync(process.cwd())
 key = serverRoot + '/assets/app/google-key.pem'
 drive = googleapis.drive('v2')
 myMail = Meteor.settings.googleSpreadsheet.mail
 serviceMail = Meteor.settings.googleSpreadsheet.serviceMail
 authClient = new (googleapis.auth.JWT)(serviceMail, key, 'key',['https://www.googleapis.com/auth/drive'], myMail)
 authClient.authorize (err, tokens) ->
    if err
      log.info 'There is error with authorize: ' + err
    else
      console.log 'everything is good'
```

**Comment by aaronjudd** [comment]
you can pin the package version you are using, so if you think the problem is with the latest release try using the previous version:

```
ongoworks:google-spreadsheets@0.4.2
```

if that works for you,  we can debug 0.5.1 some more.

**Comment by ghost** [comment]
@aaronjudd I can't install 0.5.1 version,
when I use meteor update ongoworks:google-spreadsheets, I'm getting @0.4.2_4
when I use meteor update ongoworks:google-spreadsheets --allow-incompatible-update
, I'm also getting @0.4.2_4 and this log:

```
Changes to your project's package version selections from updating package versions:       
ongoworks:google-spreadsheets  downgraded from 0.5.1 to 0.4.2_4
```

I tried to install this package (https://github.com/google/google-api-nodejs-client) for auth separately, I got same error. Does it mean that error cause of that package?
