### ISSUE TITLE
exit code 3 troubleshooting

### ISSUE THREAD

**Issue by 1jerry** [ongoworks/meteor-google-spreadsheets#6]
I was having success importing a large (42k row) Google Spreadsheet, it stopped working today.  I have made _no_ changes to either my code, my sheet's sharing, or my Google service account and I am finding no clues anywhere.

I have a console.log just before and just after my call to "spreadsheet/fetch2" so I know what line of code is triggering the error, which worked perfection find the other day with the same _hard coded_ variables:

``` javascript
 ssheet = Meteor.call("spreadsheet/fetch2", ssName, "1", {
    email: serviceEmail
  });
```

The console output is a bit odd.  I see my "before" log entry.  Then the error, which has the same format as a message coming directly from the meteor command: **=> Exited with code: 3**.  Then it seems to restart, because I'm getting my normal app start log messages again.  (I don't get the problem the second time because I'm using migrations and since it crashed _during_ a migration, the migration lock prevents a second try).

The debugging steps I've tried:
1. rename the original sheet (and the name assigned to ssName) - no effect
2. tried a different, smaller sheet that I've used before from the same Google Drive location - works
3. tried giving it a bad sheet name to see what happens. - logs that it couldn't find my name.
4. tried to no avail to figure out if these were any debugging logs or way of listing shared documents from the Google service account console.

I don't think it is an error in your code, because all the error checks I've seen seem to create a log entry, but Is it possible?  If not, how do I even start to figure out where the exit is being generated from and why?

**Comment by aaronjudd** [comment]
@1jerry I'll take a look in a few days (I'm traveling), unless anyone else can take a look.  Maybe we could add some logging options to help debug, although it sounds like it might be crashing before a log would capture the issue.  Is there more output after "=> Exited with code: 3." on the console?

**Comment by 1jerry** [comment]
The very next output is my debugging messages that indicates Meteor has
restarted.  The log message on the very next line of code after calling
fetch2 never appears.
Thanks for the reply.

## 

## Jerry

**Comment by 1jerry** [comment]
After doing further research, including looking at the node-google-spreadsheets issues, I think the issue relates to **Google** making some kind of change on April 20.  It is very strange that my spreadsheet of 300 rows of test data still works.  This has come at a bad time for me because I was ready to create my "live" website, but I cannot get the data into it!

One other **big** note, which I forgot about before:  I have frozen the version to 0.1.0 for two reasons: 1) all the newer version don't work with Windows (I'll make a separate issue), and 2) it worked.  Unfortunately, moving my app to Linux and updating to your current 0.4.0 version didn't work either, with _different_ errors.  The Linux error was:

  (STDERR) FATAL ERROR: CALL_AND_RETRY_0 Allocation failed - process out of memory 
  => Exited from signal: SIGABRT*

This is also odd since I watched the memory usage with ps and it never even got _close_ to _half_ my available memory!  Loading my 300 row test data set _also_ works on Linux.

I also tried sharing my document publicly and using the _fetch_ read-only method (which I've used successfully before - thanks for the package by the way).  Now **it** gets errors too: _Cannot read property 'title' of undefined_.  This error at least help be track down a possible Google API change.

All this sounds outside of your code, but hopefully will help track down the underlying issue(s) so it can work again.

**Comment by wrichman** [comment]
@aaronjudd Thanks for writing this tutorial! How exactly should the google-key.pem (re: step 6 below) file look when given a json file? Do you think you could provide an example with the tutorial?

Your service account should have a private key associated. Save that private key into a file named "google-key.pem" in your app's "private" folder. You might be given the key within a JSON file, in which case you need to extract and parse it into the separate PEM file (replace "\n" with actual line breaks, etc.).

**Comment by aaronjudd** [comment]
@wrichman to be honest, I'd have to re-research it.  If you have any suggestions, happy to add/edit the tutorial.
