### ISSUE TITLE
No errors on server, but spreadsheet/fetch2 call returns undefined

### ISSUE THREAD

**Issue by mkimhj** [ongoworks/meteor-google-spreadsheets#9]
Not entirely sure what's going on, the script can find my spreadsheet, as well as get through all the oauth, but I'm not receiving any data from the spreadsheet as the fetch function returns undefined.

Any ideas?

**Comment by aaronjudd** [comment]
No idea, sorry.  You might want to try the updated version `ongoworks:google-spreadsheets@0.4.2_4` that I just pushed, built with updated meteor packages.
